server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pfe_extraction
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

gemini:
  api-key: ${GOOGLE_API_KEY}
  model: gemini-2.5-flash
  base-url: https://generativelanguage.googleapis.com
